### ISSUE TITLE
xml布局中View加style属性都会报错

### ISSUE THREAD

**Issue by fengshenzhu** [fengshenzhu/Reskin1#12]
无论是系统style还是自定义style，都会报错：

```
java.lang.NumberFormatException: Invalid int: "xxxxxx"
at java.lang.Integer.invalidInt(Integer.java:138)
at java.lang.Integer.parse(Integer.java:410)
at java.lang.Integer.parseInt(Integer.java:367)
at java.lang.Integer.parseInt(Integer.java:334)
at skin.lib.SkinLayoutInflaterFactory.addSkinViewIfNecessary(SkinLayoutInflaterFactory.java:153)
at skin.lib.SkinLayoutInflaterFactory.onCreateView(SkinLayoutInflaterFactory.java:108)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:748)
... 46 more
```

系统：

```
java.lang.NumberFormatException: Invalid int: "android:style/Widget.ProgressBar.Large"
```

自定义：

```
java.lang.NumberFormatException: Invalid int: "style="@style/roomRatingBar"
```

**Comment by fengshenzhu** [comment]
暂时修复了crash，但style里属性不支持换肤

**Comment by fengshenzhu** [comment]
一般情况下通过`AttributeSet.getAttributeValue(i)`获取的值为形式为`@+id`，当有style属性时为`@style="@style/xxxxx`，不能得到style中的属性。
替换实现方式：

``` java
TypedArray typedArray = mContext.obtainStyledAttributes(set, attrs);
```
