### ISSUE TITLE
activity布局xml中有fragment报错

### ISSUE THREAD

**Issue by fengshenzhu** [fengshenzhu/Reskin1#7]
```
Caused by: android.view.InflateException: Binary XML file line #8: Class is not a View android.support.v4.app.Fragment
                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:636)
                                                               at skin.lib.SkinLayoutInflaterFactory.createView(SkinLayoutInflaterFactory.java:132)
                                                               at skin.lib.SkinLayoutInflaterFactory.onCreateView(SkinLayoutInflaterFactory.java:94)
```

**Comment by fengshenzhu** [comment]
SkinLayoutInflaterFactory.onCreateView()不应处理布局中`<fragment ... />`标签

``` java
if ("fragment".equals(name)) {
    return null;
}
```
