### ISSUE TITLE
Activity中动态添加Fragment出错

### ISSUE THREAD

**Issue by fengshenzhu** [fengshenzhu/Reskin1#9]
Fragment onCreateView()使用参数中`inflater`布局

``` java
public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
    return inflater.inflate(R.layout.fragment_a, container, false);
}
```

布局fragment xml时报错：

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
                                                       at android.view.ViewConfiguration.get(ViewConfiguration.java:364)
                                                       at android.view.View.<init>(View.java:3794)
                                                       at android.view.View.<init>(View.java:3898)
                                                       at android.view.ViewGroup.<init>(ViewGroup.java:573)
                                                       at android.widget.LinearLayout.<init>(LinearLayout.java:203)
                                                       at android.widget.LinearLayout.<init>(LinearLayout.java:199)
                                                       at android.widget.LinearLayout.<init>(LinearLayout.java:195)
                                                       at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                                                       at skin.lib.SkinLayoutInflaterFactory.createView(SkinLayoutInflaterFactory.java:126) 
                                                       at skin.lib.SkinLayoutInflaterFactory.onCreateView(SkinLayoutInflaterFactory.java:99) 
                                                       at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:190) 
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746) 
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                       at skin.demo.FragmentA.onCreateView(FragmentA.java:31) 
```

使用getActivity().getLayoutInflater()不会出错。

**Comment by fengshenzhu** [comment]
问题定位到LayoutInflater.createViewFromTag:

``` java
View createViewFromTag(View parent, String name, Context context, AttributeSet attrs,
            boolean ignoreThemeAttr) {
    ...
    if (view == null) {
        final Object lastContext = mConstructorArgs[0];
        mConstructorArgs[0] = context;
        try {
            if (-1 == name.indexOf('.')) {
                view = onCreateView(parent, name, attrs);
            } else {
                view = createView(name, null, attrs);
            }
        } finally {
            mConstructorArgs[0] = lastContext;
        }
    }
    ...
}
```

在onCreateView调用前后没有赋值给mConstructorArgs[0]，导致调用View构造函数时传参Context为空

**Comment by fengshenzhu** [comment]
LayoutInflater使用:

``` java
getActivity().getLayoutInflater()
```
